name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup directory
      run: make setup
    - name: Compilazione
      run: make

  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Installazione dipendenze
      run: sh ./.github/configure.sh
    - name: Setup directory
      run: make setup
    - name: Compilazione
      run: make CROSS_COMPILE=-mingw-w64-x86-64
